<a href="https://colab.research.google.com/github/JulexyFerrin/AI2023-2_JULEXY_FERRIN/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as jf

aux=jf.array([1,2,4,5])
print(aux)
# Tipo de arreglo
print(aux.shape)
print('------------------------------')

aux=jf.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))
print('------------------------------')

x=jf.zeros((4,4))
print(x)
print('------------------------------')


x=jf.full((4,4),5)
print(x)
print('------------------------------')


x=jf.eye(4,4)
print(x)
print('------------------------------')

x=jf.ones((4,4))
print(x)
print(x.shape)

[1 2 4 5]
(4,)
------------------------------
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)


In [ ]:
y=10*jf.random.random((4,4))
print(y)

[[7.95842359 2.50750215 2.25014808 4.10137666]
 [3.66215875 3.27532595 2.72263206 2.92183814]
 [3.24287957 6.53697002 0.10548177 8.19253639]
 [1.33464036 2.82039578 6.63562516 4.38478151]]


In [ ]:
print(y[:2,:2])

[[7.95842359 2.50750215]
 [3.66215875 3.27532595]]
------------------------------
[[0.10548177 8.19253639]
 [6.63562516 4.38478151]]


In [ ]:
print(y[:2,1:3])

[[2.50750215 2.25014808]
 [3.27532595 2.72263206]]


In [ ]:
print(y[1,1])
print('------------------------------')
print(y[2,2])

3.275325948621286
------------------------------
0.10548176723359948


In [ ]:
tmp=10*jf.random.random((5,5))
print(tmp)

[[2.08232026 4.23472776 0.20184615 3.7629833  3.02786671]
 [6.00397158 3.39732031 1.23682398 3.27256717 6.70029532]
 [7.99009412 0.1299636  5.68858488 7.93355576 9.91479149]
 [0.28011105 5.46860801 5.67004163 9.21909777 9.10405675]
 [9.26995849 4.21235473 6.65040172 0.44998674 8.19881523]]


In [ ]:
mascara=tmp>5
print(mascara)
print('------------------------------')
print(tmp[mascara])

[[False False False False False]
 [ True False False False  True]
 [ True False  True  True  True]
 [False  True  True  True  True]
 [ True False  True False  True]]
------------------------------
[6.00397158 6.70029532 7.99009412 5.68858488 7.93355576 9.91479149
 5.46860801 5.67004163 9.21909777 9.10405675 9.26995849 6.65040172
 8.19881523]


In [ ]:
mask = (tmp >=2) & (tmp<=4)
print(tmp[mask])

[2.08232026 3.7629833  3.02786671 3.39732031 3.27256717]


In [ ]:
tmp = jf.random.randint(0, 11, size=(4, 4))
print(tmp)
print('----------------------------------')
mask = jf.mod(tmp, 2) == 0
print(tmp[mask])


[[10  0  6  4]
 [ 6  4 10  9]
 [ 8  4  0  3]
 [ 9 10  3  3]]
----------------------------------
[10  0  6  4  6  4 10  8  4  0 10]


In [1]:
import numpy as np

#create an array with random inteher values between 1 and 10
a = np.random.randint(1, 11, size=(3,4))
b = np.random.randint(1, 11, size=(3,4))

print('MATRIZ A')
print(a)
print('MATRIZ B')
print(b)
print(a.shape)
print(b.shape)

print('------------------------------------------------------')

print('Adding numbers')
#plus
print(a+b)
print('Subtracting numbers')
#minus
print(a-b)
print('Multiplication numbers')
#times
print(a*b)

print('------------------------------------------------------')

print('SUMANDO')
print(np.add(a,b))
print('RESTANDO')
print(np.multiply(a,b))
print('MULTIPLICANDO')
print(np.subtract(a,b))
print('DIVIDIENDO')
print(np.divide(a,b))

MATRIZ A
[[ 9 10  3  8]
 [10  7  1  5]
 [10  1  9  7]]
MATRIZ B
[[ 9  3  7 10]
 [10  3  5  2]
 [ 2  6  3 10]]
(3, 4)
(3, 4)
------------------------------------------------------
Adding numbers
[[18 13 10 18]
 [20 10  6  7]
 [12  7 12 17]]
Subtracting numbers
[[ 0  7 -4 -2]
 [ 0  4 -4  3]
 [ 8 -5  6 -3]]
Multiplication numbers
[[ 81  30  21  80]
 [100  21   5  10]
 [ 20   6  27  70]]
------------------------------------------------------
SUMANDO
[[18 13 10 18]
 [20 10  6  7]
 [12  7 12 17]]
RESTANDO
[[ 81  30  21  80]
 [100  21   5  10]
 [ 20   6  27  70]]
MULTIPLICANDO
[[ 0  7 -4 -2]
 [ 0  4 -4  3]
 [ 8 -5  6 -3]]
DIVIDIENDO
[[1.         3.33333333 0.42857143 0.8       ]
 [1.         2.33333333 0.2        2.5       ]
 [5.         0.16666667 3.         0.7       ]]


In [2]:
a=np.random.randint(0,10,(2,3))

b=np.random.randint(0,10,(3,4))
print('MATRIZ A')
print(a)
print('MATRIZ B')
print(b)
print('----------------------------')
print('Forma 1')
print(np.dot(a,b))
print('Forma 2')
print(a.dot(b))
print(np.dot(a,b).shape)

MATRIZ A
[[8 6 6]
 [7 3 7]]
MATRIZ B
[[3 1 6 4]
 [9 8 4 9]
 [4 6 9 6]]
----------------------------
Forma 1
[[102  92 126 122]
 [ 76  73 117  97]]
Forma 2
[[102  92 126 122]
 [ 76  73 117  97]]
(2, 4)


In [3]:
a=np.random.randint(0,20,(5,3))
print(a)
print('----------------------------')
print(a.T)

[[ 2  3 12]
 [17  6 13]
 [18 18  8]
 [ 8  3 18]
 [ 0  4  3]]
----------------------------
[[ 2 17 18  8  0]
 [ 3  6 18  3  4]
 [12 13  8 18  3]]


In [4]:
a=np.random.randint(0,10,(4,3))
print(a)
b=np.array([1,0,2])
print(b)
print('-------------------------')
c=np.empty_like(a)
print(c)
x=a+b

print(np.empty_like(x))

[[6 5 5]
 [3 4 4]
 [5 6 5]
 [4 1 5]]
[1 0 2]
-------------------------
[[ 9 10  3]
 [ 8 10  7]
 [ 1  5 10]
 [ 1  9  7]]
[[4607182418800017408 4614688418178968235 4601392076421969627]
 [4605380978949069210 4607182418800017408 4612436618365282987]
 [4596373779694328218 4612811918334230528 4617315517961601024]
 [4595172819793696085 4613937818241073152 4604480259023595110]]


In [5]:
for i in range(4):
  c[i,:]=a[i,:]+b
print(a)
print('-------------')
print(b)
print('-------------')
print(c)

[[6 5 5]
 [3 4 4]
 [5 6 5]
 [4 1 5]]
-------------
[1 0 2]
-------------
[[7 5 7]
 [4 4 6]
 [6 6 7]
 [5 1 7]]


In [6]:
c=a+b
print(c)

[[7 5 7]
 [4 4 6]
 [6 6 7]
 [5 1 7]]


In [7]:
x=np.array([1,2,3])
print(x)
y=np.tile(x,(5,2))
print(y)
z=np.full((6,3),[x])
print(z)

[1 2 3]
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [8]:
a=np.random.randint(20,31,(6,6))
print(a)
print('------------------------------')
print("PROMEDIOS COMPLETOS")
aux1=np.mean(a)

print(aux1)
print('------------------------------')
print("PROMEDIOS POR FILAS")
aux2=np.mean(a,axis=1)
print(aux2)
print('------------------------------')
print('PROMEDIOS POR COLUMNAS')
print(np.mean(a, axis=0))

[[23 29 29 28 28 27]
 [30 24 28 20 26 24]
 [23 25 28 23 24 29]
 [27 23 26 24 21 26]
 [24 28 29 28 25 27]
 [20 24 25 28 30 24]]
------------------------------
PROMEDIOS COMPLETOS
25.75
------------------------------
PROMEDIOS POR FILAS
[27.33333333 25.33333333 25.33333333 24.5        26.83333333 25.16666667]
------------------------------
PROMEDIOS POR COLUMNAS
[24.5        25.5        27.5        25.16666667 25.66666667 26.16666667]
